// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerManagement.Data;

#nullable disable

namespace ServerManagement.Migrations
{
    [DbContext(typeof(ServerManagementContext))]
    partial class ServerManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServerManagement.Models.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Servers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Tokyo",
                            IsOnline = true,
                            Name = "Nebula"
                        },
                        new
                        {
                            Id = 2,
                            City = "Berlin",
                            IsOnline = true,
                            Name = "QuantumCore"
                        },
                        new
                        {
                            Id = 3,
                            City = "London",
                            IsOnline = true,
                            Name = "Phoenix"
                        },
                        new
                        {
                            Id = 4,
                            City = "Sydney",
                            IsOnline = true,
                            Name = "TitanX"
                        },
                        new
                        {
                            Id = 5,
                            City = "Tokyo",
                            IsOnline = true,
                            Name = "CyberWave"
                        },
                        new
                        {
                            Id = 6,
                            City = "London",
                            IsOnline = true,
                            Name = "Hyperion"
                        },
                        new
                        {
                            Id = 7,
                            City = "Paris",
                            IsOnline = false,
                            Name = "Aether"
                        },
                        new
                        {
                            Id = 8,
                            City = "Singapore",
                            IsOnline = false,
                            Name = "Vortex"
                        },
                        new
                        {
                            Id = 9,
                            City = "Shanghai",
                            IsOnline = true,
                            Name = "Pulsar"
                        },
                        new
                        {
                            Id = 10,
                            City = "Singapore",
                            IsOnline = true,
                            Name = "Zenith"
                        },
                        new
                        {
                            Id = 11,
                            City = "Shanghai",
                            IsOnline = false,
                            Name = "Stratos"
                        },
                        new
                        {
                            Id = 12,
                            City = "Berlin",
                            IsOnline = true,
                            Name = "Aurora"
                        },
                        new
                        {
                            Id = 13,
                            City = "Tokyo",
                            IsOnline = false,
                            Name = "Nimbus"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
